### ISSUE TITLE
Error Loading Project: Cannot load facet Scala (ggp-base-master)

### ISSUE THREAD

**Issue by mrakgr** [ggp-org/ggp-base#101]
It is not a big issue, it is just that in the latest version of [IntelliJ](http://blog.jetbrains.com/scala/2014/10/30/scala-plugin-update-for-intellij-idea-14-rc-is-out/), the Scala Facet has been replaced an now the library gives errors every time it is booted. Though it works fine regardless.

**Comment by AlexLandau** [comment]
Per https://issues.gradle.org/browse/GRADLE-3276 and https://github.com/gradle/gradle/pull/471, it looks like this will be fixed in Gradle 2.12. When that releases, we can update the Gradle wrapper to use that version.

**Comment by AlexLandau** [comment]
We've upgraded to Gradle 2.12, so hopefully this is fixed. Please reopen this issue if this error still occurs with Gradle 2.12 or later.
