### ISSUE TITLE
Add option to select all gamers in kiosk

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [ggp-org/ggp-base#127]
Currently you can pick the opponent in the kiosk, but can only play against it as a human. There should be a drop down for each player in the game, allowing you to pit two AI against each other. A minimum turn delay and/or stepping forwards and backwards through the turns would also help keep the game from flashing by instantly. Zillions of games is a propriety game that does this very well: http://www.zillions-of-games.com/demo

**Comment by AlexLandau** [comment]
Have you tried using the server application for AI-vs-AI play? The kiosk is specifically there to offer an interface for humans to input moves, and supports only a limited number of games (as only certain games have interface implementations). The server supports more games, including non-two-player games, and lets you pick arbitrary players (run by yourself using the player application or by others on their own computers).

**Comment by EmergencyTemporalShift** [comment]
The main problem with running the server as opposed to the kiosk is there is the extra steps of running the players as independent scripts and the lack of a visual game. I can live with the fact that not all games have an interface, but I want to see how the agents compare with one another visually.

**Comment by AlexLandau** [comment]
The server includes visualizations (though the UI is clearly not great at making them discoverable):

1) Click on the tab for the individual game in the middle section of the server panel
2) Click on the "Visualization" subtab within the game
3) You can then switch between turns in a third layer of tabs

I have screenshots, but am having some trouble uploading them to this thread.
