### ISSUE TITLE
Nondeterministic ProverStateMachine.getLegalMoves with recursive rules

### ISSUE THREAD

**Issue by fhars** [ggp-org/ggp-base#6]
The test of recursive rules in branch test-recursion-5d (ggp-org/ggp-base@c3b8eae2c2) fails and succeeds nondeterministically, sometimes the last step of the cycle that infers (s 1 2) seems to be missing.

**Comment by AlexLandau** [comment]
With #66, the ProverStateMachine should now handle recursion fully correctly. amazonsTorus should now give deterministic behavior, along with other games like the one in the referenced commit.
