### ISSUE TITLE
Javadoc has errors

### ISSUE THREAD

**Issue by bestlem** [ggp-org/ggp-base#78]
Compiling the javadoc gives 20 errors and many warnings.

A few are  on a setter method wiith a @return, renamed or removed parameter etc so just delete the line or correct the spelling

The others appear to be unescaped < or > in the doc so I think need replacing with &lt; or &gt; Which is not nice as this is example code

**Comment by bestlem** [comment]
See my javadoc branch for a quick fix - 

note I removed the javadoc lines complaining about JSONExceptions - the correct fix might be to add them ion code

**Comment by AlexLandau** [comment]
https://github.com/ggp-org/ggp-base/commit/e8173914dba63b4cdef9cc51006adb82023098a6
