### ISSUE TITLE
A GGP game

### ISSUE THREAD

**Issue by Bonkebo** [ggp-org/ggp-base#87]
Hi,I have a question about a GGP game.Can anybody help me?
Thanks!

Here is a very ancient game originated from China: Tiger vs Dogs.
In the above 4X4 board(5 rows,5columns), there are one tiger (represented by a white stone in the center) and 16 dogs
(represented by black stones in the perimeter).
The tiger is controlled by the tiger player and the dogs are controlled by the dog player. The tiger player
goes rst and then they take turns. Each player can go one step along the line to an adjacent position that
is not occupied.
When the tiger enters a position such that the following condition hold \two dogs are adjacent to this
position such that they three are in the same line, and also these two dogs have no adjacent dogs in the same
line", then these two dogs are killed by the tiger. If 6 dogs are killed, then the tiger player wins and the dog
player loses.
When the dogs surrounded the tiger such that there is no unoccupied adjacent position for the tiger to
move, then the tiger player loses and the dog player wins.

Write a game description in GDL (KIF form) for this game.

**Comment by AlexLandau** [comment]
You may find these resources on how to write a game in GDL helpful:

http://alloyggp.blogspot.com/2013/01/writing-game-with-gdl-sim.html
http://alloyggp.blogspot.com/2014/04/the-annotated-tic-tac-toe.html
