### ISSUE TITLE
Add ability to abandon running games in the Server app

### ISSUE THREAD

**Issue by AlexLandau** [ggp-org/ggp-base#89]
This can be convenient both when testing games or players and if the Server app were to be used for a tournament. The next-fastest alternative is the annoying process of restarting the app and reselecting the repo, the game, the players, etc.

**Comment by samschreiber** [comment]
Doesn't the "Cancel Match" button do exactly this?

**Comment by samschreiber** [comment]
![cancelmatch2](https://cloud.githubusercontent.com/assets/5640020/10116673/c7afda22-63f0-11e5-9b73-d8b0a9d29fa8.png)

(the consequence of clicking "Cancel Match" is that you end up with an aborted match, as is visible in the history that the Server app is showing in that screenshot)

**Comment by AlexLandau** [comment]
Ah, I never paid much attention to the Overview tab. Yeah, that's good enough.
