### ISSUE TITLE
Expose game versioning in GameRepository

### ISSUE THREAD

**Issue by AlexLandau** [ggp-org/ggp-base#90]
For certain applications (in my case performance testing), it would be helpful to be able to record the exact identity of a game that was used to generate information. Currently the GameRepository and Game objects don't expose the version of a loaded game, nor allow the user to request a specific game version.

**Comment by samschreiber** [comment]
getRepositoryURL is the exact identity of a game, including the version. That's used to uniquely identify the identity of a game for things like recording match histories.

**Comment by AlexLandau** [comment]
I solved this in my case by just including a hash of the game contents in the game ID. (This gets around the problem of game rulesheets occasionally changing in ways that affect performance without updating the version.)

It sounds like the URL is probably enough for other uses.
